name: Build Rachel Multiverse

on:
  push:
    branches: [ main ]
    paths:
      - '*/rachel-*/**.asm'
      - '*/rachel-*/**.s'
      - '*/rachel-*/**.c'
      - '*/rachel-*/**.h'
      - '*/rachel-*/Makefile'
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build (comma-separated, or "all")'
        required: false
        default: 'all'

jobs:
  # Build each platform repository
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [
          rachel-terminal,
          rachel-dos,
          rachel-c64,
          rachel-gameboy,
          rachel-apple2,
          rachel-atari2600,
          rachel-atari5200,
          rachel-spectrum,
          rachel-ti83
        ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: rachel-multiverse/${{ matrix.repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup build environment
        run: |
          sudo apt-get update
          case "${{ matrix.repo }}" in
            rachel-dos)
              # Install DOSBox and OpenWatcom
              sudo apt-get install -y dosbox
              ;;
            rachel-c64|rachel-apple2)
              # Install cc65
              git clone https://github.com/cc65/cc65.git
              cd cc65 && make && sudo make install && cd ..
              ;;
            rachel-gameboy)
              # Install GBDK
              wget https://github.com/gbdk-2020/gbdk-2020/releases/download/4.2.0/gbdk-linux64.tar.gz
              tar xzf gbdk-linux64.tar.gz
              echo "export GBDK_HOME=$PWD/gbdk" >> $GITHUB_ENV
              echo "export PATH=$PWD/gbdk/bin:$PATH" >> $GITHUB_ENV
              ;;
            rachel-atari2600|rachel-atari5200)
              # Install DASM
              git clone https://github.com/dasm-assembler/dasm.git
              cd dasm && make && sudo cp bin/dasm /usr/local/bin/ && cd ..
              ;;
            rachel-spectrum)
              # Install pasmo
              sudo apt-get install -y pasmo
              ;;
            rachel-ti83)
              # Install spasm-ng
              git clone https://github.com/alberthdev/spasm-ng.git
              cd spasm-ng && make && sudo cp spasm /usr/local/bin/ && cd ..
              ;;
            rachel-terminal)
              # Standard C compiler
              sudo apt-get install -y build-essential
              ;;
          esac
      
      - name: Build platform
        run: |
          if [ -f Makefile ]; then
            make clean || true
            make
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.repo }}
          path: |
            *.prg
            *.exe
            *.com
            *.gb
            *.nes
            *.bin
            *.rom
            *.dsk
            *.tap
            *.8xp
            *.a26
            *.a52
            rachel
            rachel_*

  # Create summary
  summary:
    runs-on: ubuntu-latest
    needs: build-matrix
    if: always()
    
    steps:
      - name: Generate build report
        run: |
          echo "# Rachel Multiverse Build Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Platforms Built" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Terminal ✅" >> $GITHUB_STEP_SUMMARY
          echo "- DOS ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Commodore 64 ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Game Boy ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Apple II ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Atari 2600 ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Atari 5200 ✅" >> $GITHUB_STEP_SUMMARY
          echo "- ZX Spectrum ✅" >> $GITHUB_STEP_SUMMARY
          echo "- TI-83/84 ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "*One game. Every platform. CI/CD achieved.*" >> $GITHUB_STEP_SUMMARY